CREATE TABLE DATEI(
ID SERIAL PRIMARY KEY,
HASH VARCHAR NOT NULL,
LAENGE DECIMAL NOT NULL,
NAME VARCHAR NOT NULL);

CREATE TABLE ARCHIV(
ID SERIAL PRIMARY KEY,
NAME VARCHAR NOT NULL);

CREATE TABLE DATEIARCHIV(
DATEI_ID INTEGER NOT NULL,
ARCHIV_ID INTEGER NOT NULL,
CONSTRAINT SYS_PK_DATEIARCHIV PRIMARY KEY(DATEI_ID,ARCHIV_ID),
CONSTRAINT SYS_FK_7 FOREIGN KEY(DATEI_ID) REFERENCES DATEI(ID) ON DELETE CASCADE,
CONSTRAINT SYS_FK_8 FOREIGN KEY(ARCHIV_ID) REFERENCES ARCHIV(ID) ON DELETE CASCADE);

CREATE TABLE PFAD(
ID SERIAL PRIMARY KEY ,
NAME VARCHAR NOT NULL);

CREATE TABLE DATEIPFAD(
DATEI_ID INTEGER NOT NULL,
PFAD_ID INTEGER NOT NULL,
CONSTRAINT SYS_PK_DATEIPFAD PRIMARY KEY (DATEI_ID,PFAD_ID),
CONSTRAINT SYS_FK_15 FOREIGN KEY(DATEI_ID) REFERENCES DATEI(ID) ON DELETE CASCADE,
CONSTRAINT SYS_FK_16 FOREIGN KEY(PFAD_ID) REFERENCES PFAD(ID) ON DELETE CASCADE);

CREATE VIEW DATEIINFO AS
SELECT datei.*, archive.ID as Archiv_ID, archive.name as Archiv, pfad.id as Pfad_ID, pfad.name AS Pfad
FROM datei 
INNER JOIN dateiarchiv ON datei.id= dateiarchiv.datei_id
INNER JOIN archiv on archiv.id=dateiarchiv.archiv_id
INNER JOIN dateipfad ON dateipfad.datei_ID = datei.id
INNER JOIN pfad ON dateipfad.pfad_id = pfad.id