CREATE TABLE DATEI(
ID SERIAL PRIMARY KEY,
HASH VARCHAR NOT NULL,
LAENGE DECIMAL NOT NULL,
NAME VARCHAR NOT NULL,
CONSTRAINT SYS_CT_3 UNIQUE(HASH));

CREATE TABLE ARCHIVE(
ID SERIAL PRIMARY KEY,
NAME VARCHAR NOT NULL,
CONSTRAINT SYS_CT_5 UNIQUE(NAME));

CREATE TABLE DATEIARCHIVE(
DATEI_ID INTEGER NOT NULL,
ARCHIVE_ID INTEGER NOT NULL,
CONSTRAINT SYS_PK_DATEIARCHIVE PRIMARY KEY(DATEI_ID,ARCHIVE_ID),
CONSTRAINT SYS_FK_7 FOREIGN KEY(DATEI_ID) REFERENCES DATEI(ID) ON DELETE CASCADE,
CONSTRAINT SYS_FK_8 FOREIGN KEY(ARCHIVE_ID) REFERENCES ARCHIVE(ID) ON DELETE CASCADE);

CREATE TABLE PFAD(
ID SERIAL PRIMARY KEY ,
NAME VARCHAR NOT NULL,
CONSTRAINT SYS_CT_13 UNIQUE(NAME));

CREATE TABLE DATEIPFAD(
DATEI_ID INTEGER NOT NULL,
PFAD_ID INTEGER NOT NULL,
CONSTRAINT SYS_PK_DATEIPFAD PRIMARY KEY (DATEI_ID,PFAD_ID),
CONSTRAINT SYS_FK_15 FOREIGN KEY(DATEI_ID) REFERENCES DATEI(ID) ON DELETE CASCADE,
CONSTRAINT SYS_FK_16 FOREIGN KEY(PFAD_ID) REFERENCES PFAD(ID) ON DELETE CASCADE);
